services:
  web:
    build: .
    command: python /uwc/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/uwc
    ports:
      - "8022:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5434:5432"
volumes:
  postgres_data: