services:
  web:
    build: .
    command: python /uwc/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/uwc
    ports:
      - "8022:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=phb2h2$$ibh5nv--r4nea0+eygyrr@s$$z@%9!a9k9jg2+!=135_"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5434:5432"
volumes:
  postgres_data: