# Generated by Django 5.1.3 on 2024-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWR", "Owner"),
                    ("ADM", "Admin"),
                    ("EDT", "Editor"),
                    ("VWR", "Viewer"),
                ],
                default="VWR",
                max_length=3,
            ),
        ),
    ]
