# Generated by Django 5.1.3 on 2024-11-26 11:32

import django.db.models.deletion
import locations.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "first_name_uk",
                    models.CharField(
                        max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "last_name_uk",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Division Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Division Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Division Title",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("order", locations.fields.OrderField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Branch Name")),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Branch Name"
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Branch Name"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Postcode"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "status",
                    models.CharField(
                        choices=[("HD", "Hide"), ("DY", "Display")],
                        default="HD",
                        max_length=2,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="locations.division",
                        verbose_name="Division",
                    ),
                ),
                (
                    "branch_chair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_chairs",
                        to="locations.person",
                        verbose_name="Branch Chair",
                    ),
                ),
                (
                    "parish_priest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parish_priests",
                        to="locations.person",
                        verbose_name="Parish Priest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="locations.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="locations.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone",
                "verbose_name_plural": "Phones",
            },
        ),
    ]
