# Generated by Django 5.1.3 on 2024-12-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="address_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="address_uk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_secretary",
                to="locations.person",
                verbose_name="Branch Secretary",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="other_details",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Other Details"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="other_details_en",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Other Details"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="other_details_uk",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Other Details"
            ),
        ),
    ]
