# Generated by Django 5.1.3 on 2024-11-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_division_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="description",
        ),
    ]
