# Generated by Django 5.1.3 on 2024-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_branch_address_en_branch_address_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="lat",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="branch",
            name="lng",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AddField(
            model_name="branch",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
