# Generated by Django 5.1.3 on 2024-11-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_remove_division_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["order"],
                "permissions": [("change_division_order", "Can change division order")],
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
    ]
