# Generated by Django 5.1.3 on 2024-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_branch_lat_branch_lng_branch_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="formatted_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Formatted Address"
            ),
        ),
    ]
