# Generated by Django 5.1.3 on 2024-12-02 08:46

import django.db.models.deletion
import locations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_division_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="location",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="phone",
            old_name="location",
            new_name="branch",
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="branch_chair",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_chair",
                to="locations.person",
                verbose_name="Branch Chair",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="parish_priest",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parish_priest",
                to="locations.person",
                verbose_name="Parish Priest",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branch Name"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branch Name"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="title_uk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branch Name"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name_uk",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[locations.validators.validate_uk_phone_number],
                verbose_name="Phone Number",
            ),
        ),
    ]
