# Generated by Django 5.1.3 on 2024-12-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_rename_location_email_branch_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "permissions": [("display", "Can display"), ("hide", "Can hide")],
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
    ]
